version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    expose:
     - "3306"
    volumes:
    - my-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_ROOT_PASSWORD: pass

volumes:
 my-db:
